### PR TITLE
Some updates

### PR DESCRIPTION
**Pull request by yeesian**

### CODE REVIEW

**Comment by yeesian** [comment]
@visr might you have any clues to why the build is failing for windows? https://travis-ci.org/MaximeBouton/LibSpatialIndexBuilder/jobs/453092132#L640-L644

I'll dig into the darwin builds if I can find time too.

**Comment by MaximeBouton** [comment]
Thank for helping on that, I have never work with apple OS so I will not be super helpful on this one. I can take a look at the windows one later this week.

**Comment by visr** [comment]
Regarding the Windows failure, it seems all we need to do is stop the check on resource.h from happening, because:

> Remove explicit header check - mingw does not ship with this header.

found here, where they also cross compile libspatialindex:
https://github.com/mxe/mxe/blob/8ebaf8035599e47473a0ae8fffa7a2040ad273f2/src/libspatialindex-1-fixes.patch

**Comment by visr** [comment]
So if we apply Elliot's patch from https://github.com/libspatialindex/libspatialindex/pull/124 and the patch mentioned above to the 1.8.5 release this will hopefully all work.

Here is an example of a Builder that applies a patch, though there are more:
https://github.com/JuliaLinearAlgebra/OpenBLASBuilder

**Comment by MaximeBouton** [comment]
I have a question regarding the patches, I should add something in the build that would look like: 
```
if windows 
atomic_patch -p1 "thepatch.patch
fi
```
but where should I download the patch and where should I place it?
Thanks!

Edit: I got it, I added the files in the git repo under a directory `patches`. I am trying to run the code with the patches now.

**Comment by MaximeBouton** [comment]
I created a new branch because I did not have push access to this PR:
https://github.com/MaximeBouton/LibSpatialIndexBuilder/tree/windows
I try adding the patches, they seem to be applied correctly but the build is still not passing. 

I used `julia build_tarballs.jl --verbose --debug` and manually checked the files to check that the patch was applied. 

If you have any clue of what is going on let me know.

**Comment by yeesian** [comment]
I don't actually have time to work on this PR, so I'll just leave it as-is. Thanks for following-up!

**Comment by MaximeBouton** [comment]
I managed to apply the patches correctly I think. See #2 
I will merge the second PR once the builds are all green and close this one.

**Pull request merged**
